# Generated by Django 4.2.13 on 2026-03-31 04:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalysisSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("file_name", models.CharField(blank=True, max_length=255)),
                ("total_customers", models.IntegerField(default=0)),
                ("n_clusters", models.IntegerField(default=3)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "분석 세션",
                "verbose_name_plural": "분석 세션 목록",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CustomerCluster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cluster_label",
                    models.CharField(
                        choices=[
                            ("vip", "VIP 고객군"),
                            ("churn_risk", "이탈 위험군"),
                            ("potential", "잠재 고객군"),
                            ("general", "일반 고객군"),
                        ],
                        max_length=20,
                    ),
                ),
                ("cluster_index", models.IntegerField()),
                ("customer_count", models.IntegerField(default=0)),
                ("avg_recency", models.FloatField(default=0)),
                ("avg_frequency", models.FloatField(default=0)),
                ("avg_monetary", models.FloatField(default=0)),
                ("recommendation_channel", models.TextField(blank=True)),
                ("recommendation_keywords", models.TextField(blank=True)),
                ("recommendation_message", models.TextField(blank=True)),
                ("scatter_data_json", models.TextField(blank=True, default="[]")),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clusters",
                        to="clustering.analysissession",
                    ),
                ),
            ],
            options={
                "verbose_name": "고객 군집",
                "verbose_name_plural": "고객 군집 목록",
                "ordering": ["cluster_index"],
            },
        ),
    ]
